/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Fajar
 */
public class GambarFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form GambarFullScreen
     */
    public GambarFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JPanel();
        dilucbtn = new javax.swing.JButton();
        razor = new javax.swing.JButton();
        zhonglibtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        image = new javax.swing.JPanel();
        Barcelona = new javax.swing.JLabel();
        Madrid = new javax.swing.JLabel();
        Milan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        dilucbtn.setText("Barcelona");
        dilucbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dilucbtnActionPerformed(evt);
            }
        });

        razor.setText("Real Madrid");
        razor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razorActionPerformed(evt);
            }
        });

        zhonglibtn.setText("Ac Milan");
        zhonglibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zhonglibtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonLayout = new javax.swing.GroupLayout(button);
        button.setLayout(buttonLayout);
        buttonLayout.setHorizontalGroup(
            buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dilucbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(razor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zhonglibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonLayout.setVerticalGroup(
            buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLayout.createSequentialGroup()
                .addGroup(buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dilucbtn)
                    .addComponent(razor)
                    .addComponent(zhonglibtn)
                    .addComponent(exitbtn))
                .addGap(0, 77, Short.MAX_VALUE))
        );

        getContentPane().add(button, java.awt.BorderLayout.PAGE_START);

        image.setLayout(new java.awt.CardLayout());

        Barcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Barcelona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Barca1.jpg"))); // NOI18N
        image.add(Barcelona, "2");
        Barcelona.getAccessibleContext().setAccessibleName("2");

        Madrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Madrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Madrid2.jpg"))); // NOI18N
        image.add(Madrid, "0");

        Milan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Milan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Milan3.jpg"))); // NOI18N
        image.add(Milan, "1");

        getContentPane().add(image, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dilucbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dilucbtnActionPerformed
        CardLayout cl = (CardLayout) (image.getLayout());
        cl.show(image,"0");
    }//GEN-LAST:event_dilucbtnActionPerformed

    private void razorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razorActionPerformed
        CardLayout cl = (CardLayout) (image.getLayout());
        cl.show(image,"1");
    }//GEN-LAST:event_razorActionPerformed

    private void zhonglibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zhonglibtnActionPerformed
       CardLayout cl = (CardLayout) (image.getLayout());
        cl.show(image,"2");
    }//GEN-LAST:event_zhonglibtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GambarFullScreen fullFrame = new GambarFullScreen();
                
                GraphicsDevice device =
                           GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                           device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barcelona;
    private javax.swing.JLabel Madrid;
    private javax.swing.JLabel Milan;
    private javax.swing.JPanel button;
    private javax.swing.JButton dilucbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JPanel image;
    private javax.swing.JButton razor;
    private javax.swing.JButton zhonglibtn;
    // End of variables declaration//GEN-END:variables
}
